# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-12 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menu', models.CharField(max_length=40, unique=True)),
                ('mid', models.IntegerField()),
                ('pay_menu', models.CharField(default=models.CharField(max_length=40, unique=True), max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('big_title', models.CharField(max_length=10, unique=True)),
                ('pay_title', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('content', models.CharField(max_length=50, unique=True)),
                ('price', models.IntegerField()),
                ('product_description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Xiaomi_index',
            },
        ),
    ]
