# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-16 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('cellphone', models.CharField(max_length=11, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('xiaomiid', models.IntegerField(null=True)),
                ('orderformid', models.IntegerField(null=True)),
                ('collectid', models.IntegerField(null=True)),
                ('site', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'mi_user',
                'managed': True,
            },
        ),
    ]
