# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-14 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='index',
            name='big_image',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='plate_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='select',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='big_title',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='index',
            name='content',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='index',
            name='image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='index',
            name='menu',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='index',
            name='pay_menu',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='index',
            name='pay_title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='index',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
